# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build_extract: 
    cmds:
      - echo "Building..."
      - go build -o ./dist/mod_extract ./cmd/mod_extract
    silent: true
  
  build:
    cmds:
      - task: build_extract

  run:
    cmds:
      - task: build
      - ./dist/mod_extract

  release:
    cmds:
      - echo "Releasing..."
      - fyne package -os darwin --appID com.github.cajun-code.mod_extract --icon icon.png --src ./cmd/mod_extract
      - echo "Done."
    silent: true